projectId: app-xXZB7BRSWUPPWL2Lz8FUYF
appName: hipstershop
description: Google Online Boutique
imageURL: http://image.com/image
version: 1.0.0
microservices:
  CartService:
    serviceName: cartservice
  OrderService:
    serviceName: orderservice
    avgReplicas: 2
    minReplicas: 1
    maxReplicas: 5
    maxCPU: 200m
    maxMemory: 700Mi
    dockerImage: shenalisj/sample-microservices:latest
    containerPort: 8080
    envs:
      DB_HOST:
        name: DB_HOST
        value: mysql
      DB_USERNAME:
        name: DB_USERNAME
        value: root
      MYSQL_DATABASE:
        name: MYSQL_DATABASE
        value: OrdersDB
      MYSQL_ROOT_PASSWORD:
        name: MYSQL_ROOT_PASSWORD
        value: root
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
